apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hackathon-ponto-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "/hacka-ponto-61/dev/DB_HOST"
        objectType: "ssmparameter"
        objectAlias: postgresHost
      - objectName: "/hacka-ponto-61/dev/DB_USERNAME"
        objectType: "ssmparameter"
        objectAlias: postgresUser
      - objectName: "/hacka-ponto-61/dev/DB_PASSWORD"
        objectType: "ssmparameter"
        objectAlias: postgresPassword
      - objectName: "/tech-challenge-lanchonete/dev/MAIL_API_URL"
        objectType: "ssmparameter"
        objectAlias: mailApiUrl
      - objectName: "/tech-challenge-lanchonete/dev/MAIL_API_KEY"
        objectType: "ssmparameter"
        objectAlias: mailApiKey
  secretObjects:
    - secretName: hackathon-ponto-secrets-aws
      type: Opaque
      data:
        - objectName: postgresHost
          key: postgresHost
        - objectName: postgresUser
          key: postgresUser
        - objectName: postgresPassword
          key: postgresPassword
        - objectName: mailApiUrl
          key: mailApiUrl
        - objectName: mailApiKey
          key: mailApiKey
